/* @generated by common/sync.mjs — do not edit this copy.
 * @source  elements/dual-range.mjs
 * @version 1.0.0
 * @sha256  10b1f667cfac3e46
 *
 * Edit common/elements/dual-range.mjs and re-run `node common/sync.mjs`.
 */

/* Dual-knob range slider: two thumbs on one track selecting a `{min, max}` pair.
 *
 * Registration is a function call rather than a top-level `customElements.define`
 * so this file stays byte-identical in every consuming module — each caller
 * supplies its own tag prefix. See common/DESIGN.md §2.
 */

/** Bumped only when the stylesheet contract changes. §3.2. */
export const DUAL_RANGE_MAJOR = 1;

const STYLE_CLASS = `cmn-dual-range-v${DUAL_RANGE_MAJOR}`;

/**
 * Define `<prefix>-dual-range` for one module. Idempotent: a second call with the
 * same prefix returns the existing class rather than throwing.
 * @param {string} prefix          Module-unique tag prefix, e.g. "pf1-token-randomizer"
 * @returns {typeof HTMLElement}
 */
export function defineDualRange(prefix) {
  const tag = `${prefix}-dual-range`;
  const existing = customElements.get(tag);
  if (existing) return existing;

  const Base = foundry.applications.elements.AbstractFormInputElement;

  /**
   * @extends {AbstractFormInputElement<{min: number, max: number}>}
   * @fires {Event} input   Continuously while a knob is dragged
   * @fires {Event} change  Once when a drag ends, or on a keyboard/number-field edit
   */
  class HTMLDualRangeElement extends Base {
    constructor({ value, min, max, step, padding, readout } = {}) {
      super();
      this.#opts = { value, min, max, step, padding, readout };
      this.#readGeometry();
      this._setValue(value ?? this.getAttribute("value"));
    }

    /** @override */
    static tagName = tag;

    /** @override */
    static observedAttributes = ["disabled", "min", "max", "step", "padding"];

    /** Constructor options, used as fallbacks when the matching attribute is absent. */
    #opts;

    #domainMin;
    #domainMax;
    /** The highest usable value: `domainMax` floored onto a step boundary. */
    #top;
    #step;
    #padding;
    /** Decimal places implied by `step`, used to keep float arithmetic clean. */
    #decimals;

    #track;
    #rail;
    #fill;
    /** @type {{min: HTMLElement, max: HTMLElement}} */
    #thumbs;
    /** @type {{min: HTMLInputElement, max: HTMLInputElement}|null} */
    #inputs = null;
    #readoutEl = null;

    /** Whether a value was assigned in code, which then outranks the attribute. */
    #explicit = false;

    /** Knob currently being dragged, or null. */
    #dragging = null;
    /** Pointer-to-thumb-centre offset, so grabbing a thumb does not snap it. */
    #grabOffset = 0;

    /* ---------------------------------------- */
    /*  Geometry                                */
    /* ---------------------------------------- */

    #readGeometry() {
      const attr = (name, fallback) => {
        const raw = this.getAttribute(name) ?? this.#opts?.[name];
        const n = Number(raw);
        return Number.isFinite(n) ? n : fallback;
      };

      this.#domainMin = attr("min", 0);
      this.#domainMax = attr("max", 100);
      if (this.#domainMax <= this.#domainMin) this.#domainMax = this.#domainMin + 1;

      this.#step = Math.abs(attr("step", 1)) || 1;
      this.#decimals = (String(this.#step).split(".")[1] ?? "").length;

      const span = this.#domainMax - this.#domainMin;
      this.#top = this.#round(this.#domainMin + Math.floor(span / this.#step) * this.#step);

      // Never zero: coincident thumbs would make one of them unreachable. §3.1.
      const wanted = Math.abs(attr("padding", this.#step));
      this.#padding = this.#round(Math.min(Math.max(wanted, this.#step), this.#top - this.#domainMin));
    }

    #round(v) {
      return this.#decimals ? Number(v.toFixed(this.#decimals)) : v;
    }

    #snap(v) {
      return this.#round(this.#domainMin + Math.round((v - this.#domainMin) / this.#step) * this.#step);
    }

    #snapClamp(v) {
      return Math.min(this.#top, Math.max(this.#domainMin, this.#snap(v)));
    }

    /* ---------------------------------------- */
    /*  Value                                   */
    /* ---------------------------------------- */

    /** Accepts `{min, max}`, `[min, max]`, or a "min,max" string. */
    #coerce(value) {
      if (Array.isArray(value)) return { min: Number(value[0]), max: Number(value[1]) };
      if (typeof value === "string") {
        const [a, b] = value.split(",");
        return { min: Number(a), max: Number(b) };
      }
      return { min: Number(value?.min), max: Number(value?.max) };
    }

    /** @override */
    _setValue(value) {
      const pair = this.#coerce(value);
      let lo = Number.isFinite(pair.min) ? this.#snapClamp(pair.min) : this.#domainMin;
      let hi = Number.isFinite(pair.max) ? this.#snapClamp(pair.max) : this.#top;
      if (lo > hi) [lo, hi] = [hi, lo];
      if (hi - lo < this.#padding) hi = Math.min(this.#top, this.#round(lo + this.#padding));
      if (hi - lo < this.#padding) lo = Math.max(this.#domainMin, this.#round(hi - this.#padding));
      this.#commit(lo, hi);
    }

    /** @override */
    _getValue() {
      return { ...this._value };
    }

    get value() {
      return super.value;
    }

    /** Assignment wins over the `value` attribute from here on. */
    set value(value) {
      this.#explicit = true;
      super.value = value;
    }

    #commit(lo, hi) {
      this._value = { min: lo, max: hi };
      this._internals?.setFormValue?.(`${lo},${hi}`);
    }

    /**
     * Move one knob, pushing the other ahead of it once they are `padding` apart.
     * @returns {boolean} Whether anything actually moved.
     */
    #setKnob(knob, raw) {
      const p = this.#padding;
      let { min: lo, max: hi } = this._value;
      const v = this.#snapClamp(raw);

      if (knob === "min") {
        lo = Math.max(this.#domainMin, Math.min(v, this.#round(this.#top - p)));
        if (hi - lo < p) hi = Math.min(this.#top, this.#round(lo + p));
      } else {
        hi = Math.min(this.#top, Math.max(v, this.#round(this.#domainMin + p)));
        if (hi - lo < p) lo = Math.max(this.#domainMin, this.#round(hi - p));
      }

      if (lo === this._value.min && hi === this._value.max) return false;
      this.#commit(lo, hi);
      this._refresh();
      return true;
    }

    #emit(type) {
      this.dispatchEvent(new Event(type, { bubbles: true }));
    }

    /* ---------------------------------------- */
    /*  Rendering                               */
    /* ---------------------------------------- */

    /** @override */
    _buildElements() {
      // Attributes set after construction (`createElement` then `setAttribute`, and
      // `create()`) are only visible here, so geometry and value are read a second
      // time. An assignment made before connecting still outranks the attribute.
      this.#readGeometry();
      this._setValue(this.#explicit ? this._value : this.getAttribute("value") ?? this.#opts?.value ?? this._value);

      this.classList.add("cmn-dual-range", STYLE_CLASS);
      this._internals.role = "group";

      const mode = this.getAttribute("readout") ?? this.#opts?.readout ?? "inputs";
      const children = [];

      const numberField = (knob) => {
        const input = document.createElement("input");
        input.type = "number";
        input.className = "cmn-dr-value";
        input.dataset.knob = knob;
        input.min = String(this.#domainMin);
        input.max = String(this.#top);
        input.step = String(this.#step);
        this._applyInputAttributes(input);
        return input;
      };

      if (mode === "inputs") {
        this.#inputs = { min: numberField("min"), max: numberField("max") };
        children.push(this.#inputs.min);
      }

      this.#track = document.createElement("div");
      this.#track.className = "cmn-dr-track";
      this.#rail = document.createElement("div");
      this.#rail.className = "cmn-dr-rail";
      this.#fill = document.createElement("div");
      this.#fill.className = "cmn-dr-fill";

      const thumb = (knob) => {
        const el = document.createElement("div");
        el.className = "cmn-dr-thumb";
        el.dataset.knob = knob;
        el.setAttribute("role", "slider");
        el.setAttribute("tabindex", "0");
        const label = this.getAttribute(`aria-label-${knob}`);
        if (label) el.setAttribute("aria-label", label);
        return el;
      };
      this.#thumbs = { min: thumb("min"), max: thumb("max") };
      this._primaryInput = this.#thumbs.min;

      this.#rail.append(this.#fill, this.#thumbs.min, this.#thumbs.max);
      this.#track.append(this.#rail);
      children.push(this.#track);

      if (mode === "inputs") children.push(this.#inputs.max);
      else if (mode === "text") {
        this.#readoutEl = document.createElement("span");
        this.#readoutEl.className = "cmn-dr-readout";
        children.push(this.#readoutEl);
      }

      return children;
    }

    /** @override */
    _refresh() {
      if (!this.#rail) return; // Not yet connected
      const { min: lo, max: hi } = this._value;
      const span = this.#top - this.#domainMin;
      const pct = (v) => ((v - this.#domainMin) / span) * 100;

      this.#thumbs.min.style.left = `${pct(lo)}%`;
      this.#thumbs.max.style.left = `${pct(hi)}%`;
      this.#fill.style.left = `${pct(lo)}%`;
      this.#fill.style.width = `${pct(hi) - pct(lo)}%`;

      // Each thumb reports the range it may actually occupy, not the whole domain.
      this.#applyAria("min", lo, this.#domainMin, this.#round(this.#top - this.#padding));
      this.#applyAria("max", hi, this.#round(this.#domainMin + this.#padding), this.#top);

      if (this.#inputs) {
        this.#inputs.min.value = String(lo);
        this.#inputs.max.value = String(hi);
      }
      if (this.#readoutEl) this.#readoutEl.textContent = `${lo} – ${hi}`;
    }

    #applyAria(knob, now, lo, hi) {
      const el = this.#thumbs[knob];
      el.setAttribute("aria-valuenow", String(now));
      el.setAttribute("aria-valuemin", String(lo));
      el.setAttribute("aria-valuemax", String(hi));
    }

    /* ---------------------------------------- */
    /*  Interaction                             */
    /* ---------------------------------------- */

    /** @override */
    _activateListeners() {
      const opts = { signal: this.abortSignal };
      this.#track.addEventListener("pointerdown", this.#onPointerDown.bind(this), opts);
      this.#track.addEventListener("pointermove", this.#onPointerMove.bind(this), opts);
      this.#track.addEventListener("pointerup", this.#onPointerUp.bind(this), opts);
      this.#track.addEventListener("pointercancel", this.#onPointerUp.bind(this), opts);

      for (const el of Object.values(this.#thumbs)) {
        el.addEventListener("keydown", this.#onKeyDown.bind(this), opts);
      }
      if (this.#inputs) {
        for (const el of Object.values(this.#inputs)) {
          el.addEventListener("change", this.#onFieldChange.bind(this), opts);
          // The inner fields are an implementation detail; consumers listen on the host.
          el.addEventListener("input", (event) => event.stopPropagation(), opts);
        }
      }
    }

    #valueAt(clientX) {
      const rect = this.#rail.getBoundingClientRect();
      if (!rect.width) return this.#domainMin;
      const t = Math.min(1, Math.max(0, (clientX - rect.left) / rect.width));
      return this.#domainMin + t * (this.#top - this.#domainMin);
    }

    #nearestKnob(value) {
      const { min: lo, max: hi } = this._value;
      const dLo = Math.abs(value - lo);
      const dHi = Math.abs(value - hi);
      if (dLo === dHi) return value < lo ? "min" : "max";
      return dLo < dHi ? "min" : "max";
    }

    #onPointerDown(event) {
      if (!this.editable) return;
      event.preventDefault();

      const thumb = event.target.closest?.(".cmn-dr-thumb");
      if (thumb) {
        // Grabbing a thumb is relative: hold the offset so it does not jump to the
        // pointer on the first move.
        const rect = thumb.getBoundingClientRect();
        this.#grabOffset = rect.left + rect.width / 2 - event.clientX;
        this.#dragging = thumb.dataset.knob;
      } else {
        this.#grabOffset = 0;
        this.#dragging = this.#nearestKnob(this.#valueAt(event.clientX));
        if (this.#setKnob(this.#dragging, this.#valueAt(event.clientX))) this.#emit("input");
      }

      this.#thumbs[this.#dragging].focus();
      this.#track.setPointerCapture(event.pointerId);
    }

    #onPointerMove(event) {
      if (!this.#dragging) return;
      if (this.#setKnob(this.#dragging, this.#valueAt(event.clientX + this.#grabOffset))) {
        this.#emit("input");
      }
    }

    #onPointerUp(event) {
      if (!this.#dragging) return;
      this.#dragging = null;
      this.#grabOffset = 0;
      if (this.#track.hasPointerCapture?.(event.pointerId)) {
        this.#track.releasePointerCapture(event.pointerId);
      }
      this.#emit("change");
    }

    #onKeyDown(event) {
      if (!this.editable) return;
      const knob = event.currentTarget.dataset.knob;
      const current = this._value[knob];
      let next;
      switch (event.key) {
        case "ArrowLeft": case "ArrowDown": next = current - this.#step; break;
        case "ArrowRight": case "ArrowUp": next = current + this.#step; break;
        case "PageDown": next = current - this.#step * 10; break;
        case "PageUp": next = current + this.#step * 10; break;
        case "Home": next = this.#domainMin; break;
        case "End": next = this.#top; break;
        default: return;
      }
      event.preventDefault();
      if (this.#setKnob(knob, next)) {
        this.#emit("input");
        this.#emit("change");
      }
    }

    #onFieldChange(event) {
      event.stopPropagation();
      const field = event.currentTarget;
      const parsed = Number(field.value);
      // A blank or unparseable field reverts rather than resetting to a domain end.
      if (field.value === "" || !Number.isFinite(parsed)) return this._refresh();
      if (this.#setKnob(field.dataset.knob, parsed)) {
        this.#emit("input");
        this.#emit("change");
      } else this._refresh();
    }

    /* ---------------------------------------- */
    /*  State                                   */
    /* ---------------------------------------- */

    /** @override */
    _toggleDisabled(disabled) {
      this.classList.toggle("cmn-dr-disabled", !!disabled);
      for (const el of Object.values(this.#thumbs ?? {})) el.setAttribute("tabindex", disabled ? "-1" : "0");
      if (this.#inputs) for (const el of Object.values(this.#inputs)) el.disabled = !!disabled;
    }

    /** @override */
    attributeChangedCallback(name, oldValue, newValue) {
      if (!this.isConnected || oldValue === newValue) return;
      if (name === "disabled") return this._toggleDisabled(this.disabled);
      this.#readGeometry();
      this._setValue(this._value);
      this._refresh();
    }

    /**
     * Build one from a config object, mirroring core's `HTMLRangePickerElement.create`.
     * @param {object} config
     * @returns {HTMLDualRangeElement}
     */
    static create(config) {
      const el = new this(config);
      if (config.name) el.name = config.name;
      for (const attr of ["min", "max", "step", "padding", "readout"]) {
        if (attr in config) el.setAttribute(attr, config[attr]);
      }
      if (config.value) el.setAttribute("value", `${config.value.min},${config.value.max}`);
      foundry.applications.fields.setInputAttributes(el, config);
      return el;
    }
  }

  customElements.define(tag, HTMLDualRangeElement);
  return HTMLDualRangeElement;
}
